name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login docker regsitry
      run: docker login -u ${{ secrets.DOCKER_USER }} -p  ${{ secrets.DOCKER_PASSWORD }}
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
          docker build . --file Dockerfile --tag zlzforever/nuget-cache:${{ github.ref_name }}
          docker tag zlzforever/nuget-cache:${{ github.ref_name }} zlzforever/nuget-cache
    - name: Publish the Docker image
      run: |
          docker push zlzforever/nuget-cache:${{ github.ref_name }}
          docker push zlzforever/nuget-cache
